version: '3.8'

services:

  income-follow-up-db:
    container_name: income-follow-up-db-container
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=IncomeFollowUp
      - MYSQL_ROOT_PASSWORD=<Your_password>
    ports:
      - "3307:3306"
    healthcheck: # Check if the database is ready to accept connections
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql_data:/var/lib/mysql

  income-follow-up-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: income-follow-up-app-container
    depends_on:
      income-follow-up-db:
        condition: service_healthy # Wait for the database to be ready otherwise the app will fail to start when trying to connect to the database before it is ready
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=http://192.168.1.58:8080
      - ConnectionStrings__DefaultConnection=Server=income-follow-up-db;Port=3306;Database=IncomeFollowUp;User=root;Password=<Your_password>;

volumes:
  mysql_data: