services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=<YourStrong!Passw0rd>
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  income-follow-up:
    build:
      context: ./IncomeFollowUp
      dockerfile: Dockerfile
    container_name: income-follow-up
    restart: always
    ports:
      - "7070:7070"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=IncomeFollowUp;User Id=sa;Password=<YourStrong!Passw0rd>;TrustServerCertificate=True;

volumes:
  mssql_data:
